[tool.poetry]
name = "simple-web-counter"
version = "0.1.0"
description = ""
authors = ["ysk <ysk.univ.1007@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
